# Generated by Django 4.2.21 on 2025-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('last_reviewed', models.DateTimeField(verbose_name='date last reviewed')),
            ],
        ),
    ]
