# Generated by Django 4.2.21 on 2025-05-29 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='last_reviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
