# Generated by Django 5.1.8 on 2025-05-30 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsapi', '0002_word_owner_alter_word_last_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 19, 42, 47, 819080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='word',
            name='repetitions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
