# Generated by Django 5.1.8 on 2025-05-30 20:43

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsapi', '0003_word_next_review_word_repetitions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 20, 43, 27, 345319, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('owner', 'text')},
        ),
    ]
